// facebook

export const FACEBOOK_REGISTER_REQUEST = 'FACEBOOK_REGISTER_REQUEST';
export const FACEBOOK_REGISTER_SUCCESS = 'FACEBOOK_REGISTER_SUCCESS';
export const FACEBOOK_REGISTER_FAIL = 'FACEBOOK_REGISTER_FAIL';

export const FACEBOOK_USER_LOADED = 'FACEBOOK_USER_LOADED';
export const FACEBOOK_AUTH_ERROR = 'FACEBOOK_AUTH_ERROR';

export const FACEBOOK_LOGIN_REQUEST = 'FACEBOOK_LOGIN_REQUEST';
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_FAIL = 'FACEBOOK_LOGIN_FAIL';

export const FACEBOOK_LOGOUT = 'FACEBOOK_LOGOUT';